name: 'Deploy to AWS CloudFormation'
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIAVOPT5DC3N2CS2C4F
          aws-secret-access-key: qX86fa/OkAKTubSY3Fmx3iF8YIg8aBzfsdvQA0Xv
          aws-session-token: FwoGZXIvYXdzEAAaDE2UDYZ/4x2IpXJJHyLNAcWRc4oA5mETfKRXd9O40tOVdmJ1sipRyBJIiK4X8mg3NoZKfHerM0SdNYZ1QoJpnnIeX0wVYx6P0kQ46s8v2PxWzk1v8MTZ2DGovGQobHYyfiB/ZVH/ZpT4mBzIY4ZUEvEgf3fzwhvcyZ1QHk3IWklY/2dUYPFWNNBHrbhlqx5i7LkURNhkfqjRG9t8JxfRxkXGb6JoViAA0N7bFoJiZr7bwIFES3S1gx3TgFHKEQJrYKCiZ6PGYzobAj/aamTZAP+6xtGA+UGTawA3kfIorOvvoAYyLVP1oE5U1nDNjeF5obIEjsWOamIXzZPLmSQzB0gOgUqCc3F2MNgfFQNjUitQKg==
          aws-region: 'us-east-1' 

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: test-stack
          template: lamdacreate.yaml
          no-fail-on-empty-changeset: "1"
          
